name: Deploy a Hosting via FTP

on:
  push:
    branches:
      - main  # Se ejecuta cada vez que haces push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Subir al hosting por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/   # cambia si tu carpeta es diferente
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            server.js
            README.md
